### ISSUE TITLE
Running S1TBX in IntelliJ IDEA

### ISSUE THREAD

**Issue by valgur** [senbox-org/s1tbx#12]
Hi,

I would like to work on some modifications of S1TBX (related to working with ALOS 1.5 products) but I can't find a way to get the SNAP platform run from IntelliJ IDEA to load S1TBX- (or any other toolbox) specific modules.

I followed the instructions provided in the readme strictly, except for replacing the "E:\build\SNAP" paths with my equivalent working directory.

The --patch and --cluster parameters do not seem to be having any effect, I think.

Do you have any ideas or suggestions regarding what I should do to get S1TBX-specific modules to load?

Martin

**Comment by valgur** [comment]
After looking at the logged output more closely, I found that the --cluster parameter works correctly and the S1TBX modules are found, but they fail to load. The issue seems to be caused by the
> OpenIDE-Module-Specification-Version: ${snap.nbmSpecVersion}
line in the nbm/manifest.mf files, in which the variable is not substituted when I do "mvn install". This is only happens in some of the modules, i.e. jlinda-core. But since they are a dependency to all other S1TBX modules, none of them load successfully.

**Comment by forman** [comment]
Hi valgur,

This problem should be solved on the main branch since Friday evening. Do a git pull and try again. Sorry for the inconvenience.

Norman

**Comment by forman** [comment]
Well, I forgot to git push on Friday. 
But now it should be fine.

**Comment by valgur** [comment]
Everything works as expected now. Thanks!
