### ISSUE TITLE
NullPointerException in SAR-Simulation Terrain Correction when radiometric options enabled

### ISSUE THREAD

**Issue by benjimin** [senbox-org/s1tbx#16]
This null pointer exception occurs when attempting to terrain-correct SAR imagery (from GUI or command line) using SNAP 2.0.2 (tested on both Linux and Windows systems). 

Using the menu bar in the SNAP GUI:
Radar→Geometric→Terrain Correction→SAR-Simulation Terrain Correction,
choose a source product and proceed to the fourth tab of the dialog window,
check _"Apply radiometric normalisation"_ and _"Save Gamma0 band"_,
proceed to the final tab (error appears in red). Alternatively, instead of proceeding to the final tab, clicking Run produces an error window with the message:

_"4-SARSim-Terrain-Correction: org.esa.snap.core.gpf.OperatorException due to java.lang.NullPointerException"_

The dialog window is also generally glitchy (the radiometric options tend to change or grey-out when flicking between tabs). However, the SARSim geometric corrections seem to work if the radiometric corrections are turned off.

S1A_IW_GRDH_1SDV_20150223T090912_20150223T090925_004748_005E1F_4B90.zip was used as the test data. I replicated the same error when using the interactive GraphBuilder tool, and with the command line batch interface (gpt). 

Is this a known issue, and is there any work-around for performing all terrain corrections (i.e. **both geometric and radiometric**) to Sentinel-1A data?

**Comment by lveci** [comment]
Thanks Benjimin, we're addressing the issue now.

**Comment by lveci** [comment]
fixed NPE and UI inconsistencies
