### ISSUE TITLE
Error for external DEM

### ISSUE THREAD

**Issue by FabianVista** [senbox-org/s1tbx#2]
Hi, 
I get an error message when trying to do the SAR Terrain Correction by reading in an external DEM(GeoTiff):
"Operator ´RangeDopplerGeocodingOp`: Value for `DigitalElevationModel` is invalid: `External DEM`"
This occurs using the GUI as well as the command line option.  
Any Idea what might cause this error message?
Thanks,
Fabian

**Comment by lveci** [comment]
Works fine in current release
