### ISSUE TITLE
Minor glitchiness of radar radiometric calibration operator interface in graph builder

### ISSUE THREAD

**Issue by benjimin** [senbox-org/s1tbx#22]
Using the calibration operator, in the graph builder, two alternate option panes are possible (s1tlbx/SNAP v.4.0.0 tested on linux 64):

Pane A contains options to "save as complex output" and "create beta0 virtual band".
Pane B contains options to "output sigma0 band" and "output beta0 band".

The behaviour of the interface seems glitchy. After connecting the graph it took a fair bit of random clicking (switching between tabs while different options were checked) to switch from A to B, and I didn't find a way to switch back again from B to A (except by adding a replacement Calibration node to the graph).

In my case the intended graph was to Read (a S1 GRD scene), apply orbit, remove border noise, calibrate (producing beta0 not sigma0 nor virtual bands), flatten, and write.

**Comment by grousel** [comment]
Hi, we are consolidating our issue tracking into JIRA.  Further updates to this issue can be found at https://senbox.atlassian.net/browse/SITBX-610.
