### ISSUE TITLE
Interferometric: Phase-to-Elevation gives Null Pointer Exception

### ISSUE THREAD

**Issue by zy2lin** [senbox-org/s1tbx#24]
After importing unwrapped image from SNAPHU to the original product. I tried to run phase-to-elevation to the file. The tool kept giving "Null Pointer Exception", not sure which part went wrong. The unwrapped phase image was not terrain-corrected, and filtered using Goldstein Filter. 
![image](https://cloud.githubusercontent.com/assets/13650631/17680013/16f3bbec-630c-11e6-97a2-8f6efaeef296.png)

One other thing, Phase-to-Displacement works fine, but Phase-to-Height does not run on this file.

**Comment by muhammadnurulfahmi** [comment]
hello, i have the same issue. I got error Java.Lang.Nullpointer exception when try to convert phase to elevation. Can anyone solved this issue?

**Comment by jun--lu** [comment]
The problem has been fixed. The fix should be in SNAP V 6.0.

**Comment by joshtu2016** [comment]
Hello, i got the same Error (Java.lang.NullPointer exception) when I use 'Phase to Elevation' with SNAP V 6.0 ... also then I use 'Phase to Height' nothing is happens, also no error message. What is the problem? I working with S1 Fogo Volcano 2014 datset (03.Nov/27.Nov) from s1 tutorials.
