### ISSUE TITLE
java.lang.NullPointerException with SAR image terrain correction

### ISSUE THREAD

**Issue by lefortm** [senbox-org/s1tbx#28]
Hello, 

I am encountering the same problem as mentioned here : https://github.com/senbox-org/s1tbx/issues/16

It says it has been corrected, but it can not make it work. I encounter a java.lang.NullPointerException written in red at the bottom of the SAR-Simulation Terrain Correction when I try to terrain correct a stack of Sentinel 1 images with an external DEM. I haven't tried with a proposed DEM.

 I am running under SNAP 5.0.0.
Hoping the messages file is the correct one, but I can't attach it to this message, for an unknown reason (says "We don't support that file type".) I can send it to you by email if you give me an email adress.

Thanks a lot, 
Max

**Comment by grousel** [comment]
Thank you for logging this.  We are now tracking issues in JIRA, the ID of this report is https://senbox.atlassian.net/browse/SITBX-609
