### ISSUE TITLE
A problem occurred during the target product initialisation

### ISSUE THREAD

**Issue by xiaolan1989** [senbox-org/s1tbx#3]
I have installed the S1 toolbox to process the Sentinel SAR data.
Every time when I try to use the S1 Toolbox to Remove Antenna Pattern for the SAR data, it gives me the following error:
![image](https://cloud.githubusercontent.com/assets/12063299/7269184/00bda816-e904-11e4-88fa-8c6788ad4cdf.png)
I have reinstall the software, but error occur everytime.
I also search for help from website, but there is no information about this problem.
Could anyone tell me how to solve this problem?

**Comment by lveci** [comment]
This operator is intended for ERS missions not Sentinel-1. You do not need to remove the antenna pattern for Sentinel-1. I will add better error check.

**Comment by xiaolan1989** [comment]
Thanks very much for your reply.
What do you mean" You do not need to remove the antenna pattern for Sentinel-1." ? I do not need to do the Radimometric for the Sentinel-1 SAR data?
Did I just do the 1. Geometric correction (orho rectification) 2. Speckle filtering to the sentinel SAR data？
As for the Geometric correction, I use the Geometric -->Terrain Correction-->Range-doppler terrain correction. Is it right?  When I select the SRTM 2 Sec(auto download) for the Digital elevation Model, The calculating speed is really very slowly.
Thanks again for your consideration of this question.

**Comment by lveci** [comment]
You should apply calibration for S1, just not antenna pattern removal
Also, don't speckle filter after geometric correction, if you have to do it, do it before.

**Comment by xiaolan1989** [comment]
Thanks again for your help. I will try to process the SAR data follow your suggestion. 
Best regards.  O(∩_∩)O~
