### ISSUE TITLE
S-1B Terrain correction problem

### ISSUE THREAD

**Issue by Vekerdy** [senbox-org/s1tbx#30]
S-1B image could not be terrain corrected. S-1A images were terrain corrected from the same region and with the same pre-processing steps without problem.

Used: s1tbx 3.0.3
Symptom: no error messages, but empty Range-Doppler TC products. 
Input: see attached.

[Subset.zip](https://github.com/senbox-org/s1tbx/files/893115/Subset.zip)

Any suggestion is welcome.

Zoltán

**Comment by marpet** [comment]
Meanwhile SNAP 5(.0.4) is available. Would you mind to try it with this new version? 
http://step.esa.int/main/download/

**Comment by lveci** [comment]
We don't support version 3. This is quite old and before the launch of S1B.
It should work fine with the current version 5.

Luis Veci
Software Lead
Array Systems Computing Inc.
Toronto, Ontario Canada
+1 416-736-0900 x298
www.array.ca

**Comment by Vekerdy** [comment]
I have downloaded yesterday the new version (it is a pity that the automatic update does not work from v.3 to v5, so I did not realize that my version is not the latest… Sorry.)

I shall be back to you after some testing.

Zoltán

**Comment by Vekerdy** [comment]
Dear Luis,

I have checked the latest version of S1tbx and the processing chain, that did not work properly in version 3, now worked without problems. Thank you for the clarifications.

Best regards,

Zoltán

Btw., It is a pity that when you work with v3, the automatic upgrade does not realize that there is already a v5 on the market. This was tricking me a bit.

**Comment by Vekerdy** [comment]
Dear Marco,

I have checked the latest version of S1tbx and the processing chain, that did not work properly in version 3, now worked without problems. Thank you for the clarifications.

Best regards,

Zoltán

Btw., It is a pity that when you work with v3, the automatic upgrade does not realize that there is already a v5 on the market. This was tricking me a bit. I know, I could have kept my eyes open for the news around…

**Comment by Vekerdy** [comment]
Thank you.

Zoltán
