### ISSUE TITLE
NullPointerException in Radiometric Terrain Flattening

### ISSUE THREAD

**Issue by mirzawaqar** [senbox-org/s1tbx#33]
Hello Everyone, 

I was trying to perform Radiometric Terrain Flattening on ALOS-2 Quad-Pol data in [T3] format using SNAP. Every time I try to execute this procedure, I am getting java.lang.NullPointerException. Can anyone guide me how to fix it? 

Kind Regards

**Comment by borlafgis** [comment]
I am hitting the same wall trying use the algorithm with Sentinel-1 data a 5m dem

**Comment by grousel** [comment]
Hello, thank for you logging this.  We are now tracking issues in JIRA, the ID is https://senbox.atlassian.net/browse/SITBX-607
