### ISSUE TITLE
S1TBX Terrain-Correction can introduce negative backscatter values

### ISSUE THREAD

**Issue by S0sh0rt** [senbox-org/s1tbx#35]
bicubic interpolation of backscatter during terrain correction can produce negative backscatter values. The negative values should be set to zero since they can detrimentally affect subsequent processes. Other cubic, and sine resampling may also create negative values. Nearest-neighbor and bi-linear should not produce negative values by definition.

**Comment by grousel** [comment]
Hello, thank you for this report.  We are moving our issue tracking to JIRA and you can follow updates here https://senbox.atlassian.net/browse/SITBX-606
