### ISSUE TITLE
How to get the resample to work in the software SNAP?

### ISSUE THREAD

**Issue by bhwzy** [senbox-org/s1tbx#39]
I encountered a problem with the S-1 SLC data,when i run the SNAP software to get the spatial subset that I want. The  SLC data was required to resample before subset, but the resample processing was always show  out of memory error. Would you like to give me some advices on this processing?

**Comment by marpet** [comment]
How much memory does your computer have? This kind of reprocessing can be memory demanding.

**Comment by bhwzy** [comment]
firstly, thanks a lot for your reply.
my destop computer has a memory about 8G,
if like that how can i get the subset that i need for research?

**Comment by lveci** [comment]
For S-1 SLC products that message should not show up. You wouldn't resample the data. You should use the TOPS Split to subset a subswath or bursts. You can also use the TOPS deburst and merge to form a regular raster and then you can subset as usual. Have a look at the tutorials.

**Comment by grousel** [comment]
@bhwzy I'm going back to an old thread but just curious about whether the guidance posted resolved the issue - or whether we should still be looking into this.

**Comment by grousel** [comment]
Closing because we are no longer using issues in git to track reports.  No new JIRA item created as the guidance provided may have resolved issue.
