### ISSUE TITLE
Final Deformation-Interferogram gets missaligned.

### ISSUE THREAD

**Issue by cbalint13** [senbox-org/s1tbx#4]
Dear All,

1. I went through Graph->InSAR Graph->Deformation Preprocessing with two products.
2. The two products where "debursted" by SAR Processing->S1 TOPS->S1 TOPS Deburst.
3. I reprojected into WGS84 the final resulted "Phase" channel of my interest.

- The final deformation-interferogram gets miss-aligned with hundred of meters. I knew there is a water-dam but displayed deformation is not there, also i know some other deformation that are displayed well but not at their right place. I suspect a bug in the toobox thus interferogram is miss-aligned.

- Also i attach this photo showing the debursted product in pseudo RGB (R=VV,G=VH,B=(VV+VH)/2) which fits perfect with any WGS84 data, overlapped with deformation-phase-interferogram. The interferogram clearly is out of permitted extend !

![s1a-tbx-bad-deform](https://cloud.githubusercontent.com/assets/3974360/7452478/9a3a4222-f266-11e4-8f31-d529f7512ea8.png)

**Comment by lveci** [comment]
I don't believe you are processing the TOPS data correctly. You should be using TOPS Coregistration on each subswath, then the interferogram, topo phase removal, TOPS deburst and the then TOPS merge of all swaths. Do not do any reprojection. As a final step you may terrain correct if desired in a particular projection.

**Comment by cbalint13** [comment]
@lveci ,

   Thank you for the kind answer ! I am not an expert in InSAR i am trying to figure out the proper way for the workflow over sentinel1a kind of data.

   Furthermore for predefined workflow graphs i am trying to use the ones named "TOPSAR Coreg Interferogram IW All Swaths" or the "TOPSAR Coreg Interferogram" using two SLC IW product pairs but booth fails with:

"Back-geocoding metadata attribute 'c0' not found""

What does this exactly means ?

**Comment by yutaxsato** [comment]
Sorry for overtaking..Really a good discussion, I'm also suffering from the same. Additionally, @lveci  "you should be using TOPS Co-registration on each sub swath" the sub swath mean each IW1, IW2, IW3 files inside the SLC IW product? Having command line feature for the co-registration would be great similiar to other functionalty. Thanks for your response.

**Comment by cbalint13** [comment]
@yutaxsato , i reopened with the bug report #5 . I tried the mentioned by you using s1tbx dedicated menus for TOPS processing.

**Comment by yutaxsato** [comment]
@lveci The last step as you mentioned is really the 'terrain correction'? Is not it 'ellipsoid correction' to get in geographic projection? Sorry for writing you often in your busy time...

**Comment by cbalint13** [comment]
* Well, this below is obvious:

New in S1TBX 1.1.1

Automatic download of S-1 POE and RES orbits
Fix TOPS Coregistration for products starting at different bursts
Fix TOPS Coregistration to extend DEM for high elevation areas
Fix TOPS Coregistration to compute burst offset from middle of burst
Burst to remove invalid pixel areas
Fix SLC slice assembly
Flat-Earth phase to use average terrain height
Handle bistatic interferogram for TanDEM-X
Generalized Freeman Durden (RVOG) Decomposition

**Comment by lveci** [comment]
@yutaxsato Range Doppler Terrain Correction should generally be used if a DEM is available.
SAR Simulation Terrain Correction is used when the product may not be accurately georeferenced such as with some ERS-1.
Range Doppler Ellipsoid Correction is only used when you don't have a DEM such as for sea ice analysis.
