### ISSUE TITLE
Line/pixel indexing inconsistencies

### ISSUE THREAD

**Issue by estebanag** [senbox-org/s1tbx#40]
I've been reviewing the [`InterferogramOp`](https://github.com/senbox-org/s1tbx/blob/master/s1tbx-op-insar/src/main/java/org/esa/s1tbx/insar/gpf/InterferogramOp.java#L613
) operator and I see that it assumes one-based indexing for both pixel and line dimensions.

However, the [`SLCImage`](https://github.com/senbox-org/s1tbx/blob/master/jlinda/jlinda-core/src/main/java/org/jlinda/core/SLCImage.java) class uses these indices in an inconsistent manner (see examples below). I can fix all these inconsistencies myself and create a merge request, but before doing that, it would help me if one of the contributors maintaining this repo could let me know what their preference is (i.e., either one- or zero-based indexing). I propose using zero-based indexing.

Examples of one-based indexing for both pixel and line dimensions:
- https://github.com/senbox-org/s1tbx/blob/master/jlinda/jlinda-core/src/main/java/org/jlinda/core/SLCImage.java#L138-L139
- https://github.com/senbox-org/s1tbx/blob/master/jlinda/jlinda-core/src/main/java/org/jlinda/core/SLCImage.java#L314

Example of zero-based indexing for both pixel and line dimensions (`AbstractMetadata.subset_offset_x` and `AbstractMetadata.subset_offset_y` are zero when reading an original product):
- https://github.com/senbox-org/s1tbx/blob/master/jlinda/jlinda-core/src/main/java/org/jlinda/core/SLCImage.java#L215-L219

Examples of zero-based indexing for pixel dimension:
- https://github.com/senbox-org/s1tbx/blob/master/jlinda/jlinda-core/src/main/java/org/jlinda/core/SLCImage.java#L340-L347
- https://github.com/senbox-org/s1tbx/blob/master/jlinda/jlinda-core/src/main/java/org/jlinda/core/SLCImage.java#L355-L362

Example of one-based indexing for line dimension:
- https://github.com/senbox-org/s1tbx/blob/master/jlinda/jlinda-core/src/main/java/org/jlinda/core/SLCImage.java#L367-L370

Example of zero-based indexing for line dimension:
- https://github.com/senbox-org/s1tbx/blob/master/jlinda/jlinda-core/src/main/java/org/jlinda/core/SLCImage.java#L373-L376

**Comment by estebanag** [comment]
Hi @lveci, I was wondering if you've experienced any unexpected results due to this.

**Comment by grousel** [comment]
Thank you for reporting this.  We are now tracking open items in https://senbox.atlassian.net/browse/SITBX-605
