### ISSUE TITLE
Terrain correction error

### ISSUE THREAD

**Issue by narifir** [senbox-org/s1tbx#41]
I am running snap in ubunut. When I try to terrain correct a subset that is calibrated and speckle filtered (with no elevation mask option on), I get the following error:

An internal error occurred during the target product processing.
Type: GLException
Message: AWT-EventQueue-0: X11GLXContext.createContextImpl ctx !ARB, profile > GL2 requested (OpenGL >= 3.0.1). Requested: GLProfile[GL3bc/GL3bc.hw], current: 3.0 (Compat profile, ES2 compat, FBO, hardware) - 3.0 Mesa 17.2.4

Please help! Cheers

**Comment by grousel** [comment]
https://senbox.atlassian.net/browse/SITBX-604 is the new ID for tracking this.  We have moved issue tracking to JIRA.  Thank you for reporting this issue.
