### ISSUE TITLE
Create Satck

### ISSUE THREAD

**Issue by sergiomelo37** [senbox-org/s1tbx#46]
258/5000
I'm having trouble with the "Create Stack" tool. I'm using Ubuntu 18.04 and SNAP 6.0. When joining the two IW-GRDH images, the following error appears:

  [Nodeld: 2-CreateStack] org.jblas.NativeBlas.dgemm (CCIIID [DII [DIID [DII] V

==================================
![captura de tela de 2018-05-27 18-29-07](https://user-images.githubusercontent.com/38961653/40591300-b8940a08-61dc-11e8-841c-b54fe2b84291.png)

**Comment by sergiomelo37** [comment]
I solved the problem by installing the program "libgfortran3" with the following commands:

sudo apt-get update

sudo apt-get install libgfortran3

**Comment by windmill31** [comment]
I've got the same issue under Fedora 27 and SNAP 6.0.3, 5.0, 5.0.8 and 4.0

![snap_issue](https://user-images.githubusercontent.com/40263852/41404036-1b856596-6fbe-11e8-8038-c6985403bf80.png)

I guess installing libraries won't change anything as Fedora has not SNAP in its repositories; I use the Unix downloaded version.

**Comment by grousel** [comment]
Hello, thank you for the report.  We are moving issue tracking to JIRA, the new ID for this report is https://senbox.atlassian.net/browse/SITBX-603
