### ISSUE TITLE
corp.array.ca is offline 

### ISSUE THREAD

**Issue by wselwood** [senbox-org/s1tbx#47]
Build relies on a repository at http://corp.array.ca/nest-web/mavenrepo which is not currently responding.

**Comment by marpet** [comment]
Probably you haven't updated for a while.
Since 9th of March the repository is removed.
73d56ab7f2923f56de118d08bf2014d582fd44ac

**Comment by wselwood** [comment]
Doh ... Did a pull but end up in a detached head state. Thanks for the hint
