### ISSUE TITLE
QCScraper returns invalid links to Sentinel orbit files

### ISSUE THREAD

**Issue by jdries** [senbox-org/s1tbx#49]
The Sentinel toolbox tries to download orbit files first from the step website, then from qc website, which is needed when processing recent products.

The download from the qc website fails, because the link inside the html is not correctly parsed.
Current code:
```
 if(!currentList.contains(link)) {
                            fileList.add(elem.text());
}
```
This eventually generates incorrect url's like:
https://qc.sentinel1.eo.esa.int/aux_resorb/S1B_OPER_AUX_RESORB_OPOD_20180713T092846_V20180713T051418_20180713T083148

The link element looks like:
`<a href="http://aux.sentinel1.eo.esa.int/RESORB/2018/07/13/S1A_OPER_AUX_RESORB_OPOD_20180713T132624_V20180713T092151_20180713T123921.EOF">S1A_OPER_AUX_RESORB_OPOD_20180713T132624_V20180713T092151_20180713T123921</a>`
So simply reading the href attribute instead of the element text should already help quite a bit.

**Comment by jdries** [comment]
A better option might be to use this rest API: 
https://qc.sentinel1.eo.esa.int/api/v1/?product_type=AUX_RESORB
which would allow you to avoid html scraping.

**Comment by grousel** [comment]
JIRA issue tracking ID https://senbox.atlassian.net/browse/SITBX-601
The issue is now obsolete, as Scraper is no longer used in the product.
