### ISSUE TITLE
Back-geocoding metadata attribute 'c0' not found

### ISSUE THREAD

**Issue by cbalint13** [senbox-org/s1tbx#5]
@lveci ,

Thank you for the kind answer over #4 !

   For predefined workflow graphs (i found them very usefull) i am trying to use the ones named "TOPSAR Coreg Interferogram IW All Swaths" or the "TOPSAR Coreg Interferogram" using two SLC IW product pairs but booth graphs fail with:

"Back-geocoding metadata attribute 'c0' not found"

What does this exactly means ? Do i need more preprocesing, or its some bug !?

  I am not an expert in InSAR, i am trying to figure out the proper way for the workflow with sentinel1a kind of data. However will try your proposed workflow at #4 one for each step.

With Respect,
~Christian.

**Comment by yutaxsato** [comment]
@cbalint13, @lveci  I would like to inform you guys that when I used "S-1 TOPS Co-registration" in Sentinel-1 Toolbox (in latest version 1.1.1) by reading two zip files, and applying Orbit file (Auto-download or Restituded), the files are successfully co-registered. So, @cbalint13 what version you are using, and did you apply orbit file during "S-1 TOPS Co-registration" process?

**Comment by cbalint13** [comment]
@yutaxsato ,

Thanks for the feedback ! 

* I was using 1.1.0, it was latest of last week (~7 days ago). 
* I will try 1.1.1, seems to be newer !
