### ISSUE TITLE
Graph Builder moving very slowly after update installation

### ISSUE THREAD

**Issue by Jessie5** [senbox-org/s1tbx#50]
I recently updated SNAP. Before the update I created a Graph using the Graph Builder. This series of processes was working smoothly and efficiently just last week. On average the entire process took 35-45 minutes. The processes include Calibration, Speckle-Filter, SAR-Simulation, Range Doppler Terrain Correction. 
Now after the update I needed to re-process several of my files using the same graph that I built. Now it takes about 5-6 hours to complete. Additionally, the exported GeoTiffs that I'm making of these files in order to load in ArcMap, seem to be missing their projection data. Do you have some insight into the problems I'm running into?

Thank you

**Comment by grousel** [comment]
We are moving issue tracking into JIRA.  This item is now tracked under https://senbox.atlassian.net/browse/SITBX-600
