### ISSUE TITLE
Nodata band when use Radiometric terrain flattening on ENVISAT 2010 product

### ISSUE THREAD

**Issue by marpet** [senbox-org/s1tbx#51]
_From @FZaf on July 28, 2018 7:23_

Goodmorning, 
i would elaborate a 2010 ENVISAT product; i activate Debrust and calibration, system creates sigma HH bands, than i convert each Sigma band into beta0 band and execute the Radiometric terrain flattening; only the first band works, other bands are full of nodata values.
I miss something or it's a problem (maybe due to the old dataset i used)?
thanks
Francesco

_Copied from original issue: senbox-org/snap-engine#111_

**Comment by grousel** [comment]
We are moving issue tracking to JIRA, further updates will be tracked at https://senbox.atlassian.net/browse/SITBX-599
