### ISSUE TITLE
NullPointerException in TerraSarXProductReader

### ISSUE THREAD

**Issue by montimaj** [senbox-org/s1tbx#52]
I am trying to open quad-pol TDX-TSX CoSSC product in snap and it is showing a NullPointerException. It works fine with dual-pol CoSSC product. There is a thread (https://forum.step.esa.int/t/tandem-x-cossc-error-caused-by-data-format/5552/12) on the snap forum regarding this, however, no solution has been provided yet.

**Comment by grousel** [comment]
Thank you for the report and link to the other thread.  We are tracking our open issues in JIRA going forward and future updates will be part of https://senbox.atlassian.net/browse/SITBX-615
