### ISSUE TITLE
Ocean Object Detection - Can not export geometry

### ISSUE THREAD

**Issue by TerezaSm** [senbox-org/s1tbx#53]
In SNAP v6 S1TBX (6.0.3) there seems to be a bug in the geometry export. Once the Object Detection is executed and the new layer containing the vector layer ShipDetections is created, it is not possible to export the vector to shapefile. I remember this error in the earlier versions of SNAP 5 (June 2017), it has later been fixed with some update and now it seems to reoccur again. 

Error message:
Can not export geometry.
java.io.IOException: Could not find attribute ShipDetections (mul count: 0)

**Comment by grousel** [comment]
Thank you for the report, we are consolidating issue tracking into JIRA.  This item is tracked as https://senbox.atlassian.net/browse/SITBX-597 going forward.
