### ISSUE TITLE
SliceAssembly is missing data

### ISSUE THREAD

**Issue by j08lue** [senbox-org/s1tbx#54]
Hi s1tbx maintainers, I am running `SliceAssembly` to join four consecutive S1 SLC images:

![image](https://user-images.githubusercontent.com/3404817/45620242-83845900-ba7c-11e8-999c-8c813caf816a.png)
![image](https://user-images.githubusercontent.com/3404817/45620315-c34b4080-ba7c-11e8-8ccc-4fb90b6e796a.png)
![image](https://user-images.githubusercontent.com/3404817/45620337-d78f3d80-ba7c-11e8-9ac3-c12554e86504.png)
![image](https://user-images.githubusercontent.com/3404817/45620365-eaa20d80-ba7c-11e8-95f5-11ba28d4b0f1.png)

But the assembled result is missing data in the south (the north coast of Germany):

![image](https://user-images.githubusercontent.com/3404817/45620654-e7f3e800-ba7d-11e8-87b5-4a8452cb7bde.png)

However, when I run the same graph and omit the north-most image, the south-most data is included:

![image](https://user-images.githubusercontent.com/3404817/45621004-16be8e00-ba7f-11e8-901b-e85143efd544.png)

Here is my graph:

![image](https://user-images.githubusercontent.com/3404817/45621025-2c33b800-ba7f-11e8-93e0-0737f834848d.png)

```xml
<graph id="Graph">
  <version>1.0</version>
  <node id="SliceAssembly">
    <operator>SliceAssembly</operator>
    <sources>
      <sourceProduct.4 refid="ProductSet-Reader"/>
    </sources>
    <parameters class="com.bc.ceres.binding.dom.XppDomElement">
      <selectedPolarisations>VV</selectedPolarisations>
    </parameters>
  </node>
  <node id="TOPSAR-Split">
    <operator>TOPSAR-Split</operator>
    <sources>
      <sourceProduct refid="SliceAssembly"/>
    </sources>
    <parameters class="com.bc.ceres.binding.dom.XppDomElement">
      <subswath>IW1</subswath>
      <selectedPolarisations/>
      <firstBurstIndex>1</firstBurstIndex>
      <lastBurstIndex>28</lastBurstIndex>
      <wktAoi/>
    </parameters>
  </node>
  <node id="Write">
    <operator>Write</operator>
    <sources>
      <sourceProduct refid="TOPSAR-Split"/>
    </sources>
    <parameters class="com.bc.ceres.binding.dom.XppDomElement">
      <file>assembled.dim</file>
      <formatName>BEAM-DIMAP</formatName>
    </parameters>
  </node>
  <node id="ProductSet-Reader">
    <operator>ProductSet-Reader</operator>
    <sources/>
    <parameters class="com.bc.ceres.binding.dom.XppDomElement">
      <fileList>S1B_IW_SLC__1SDV_20180703T053055_20180703T053122_011642_01568A_3C50.zip,S1B_IW_SLC__1SDV_20180703T053120_20180703T053147_011642_01568A_EFF9.zip,S1B_IW_SLC__1SDV_20180703T053145_20180703T053213_011642_01568A_1EE3.zip,S1B_IW_SLC__1SDV_20180703T053211_20180703T053238_011642_01568A_FCC4.zip</fileList>
    </parameters>
  </node>
  <applicationData id="Presentation">
    <Description/>
    <node id="SliceAssembly">
      <displayPosition x="165.0" y="61.0"/>
    </node>
    <node id="TOPSAR-Split">
      <displayPosition x="300.0" y="61.0"/>
    </node>
    <node id="Write">
      <displayPosition x="415.0" y="61.0"/>
    </node>
    <node id="ProductSet-Reader">
      <displayPosition x="15.0" y="61.0"/>
    </node>
  </applicationData>
</graph>
```

I encounter this issue in SNAP 6.0.4 with up-to-date modules, both on an Ubuntu machine with 400 GB RAM (via `gpt`) and a Windows machine with 32 GB RAM via GUI. I tried tweaking the `gpt.vmoptions`, setting e.g. `-Xmx64G`, but it seemed to have no effect at all on memory usage or outcome.

Do you have any clue why this could be happening?

**Comment by valgur** [comment]
@j08lue Are you asking this or are you forwarding a message from someone else? This question seems better-suited for the [STEP Forum](https://forum.step.esa.int/).

**Comment by j08lue** [comment]
@valgur I thought the GitHub issues are for bugs and this was a bug. Seems like both assumptions were not correct - the latter since you seem to have a solution?

I opened a thread on the forums instead. Can you please explain (there) how to adjust the `BurstIndex`?

https://forum.step.esa.int/t/sliceassembly-is-missing-data/11657

**Comment by valgur** [comment]
Oh, I am so used to seeing you on the sentinelsat repo @j08lue that I did not even notice that this actually is the s1tbx one. I automatically assumed you were posting on the former and was quite confused. Sorry for coming off as rude implying thar it's not okay to post here. That was not my intention at all.

**Comment by j08lue** [comment]
No worries @valgur. 😄 Pleasant surprise to get your response here. And thanks for the solution.
