### ISSUE TITLE
TopographicPhase Unexpected exception

### ISSUE THREAD

**Issue by fokouop** [senbox-org/s1tbx#57]
A java.lang.UnsatisfiedLinkError exception has occurred.
	Click Show Details or see the messages.log file located in your /home/abouga/.snap/system/var/log folder.

**Comment by grousel** [comment]
We are consolidating our issue tracking into JIRA.  Going forward this can be tracked as https://senbox.atlassian.net/browse/SITBX-596.  Out of curiosity, is this a reproducible error @fokouop ?
