### ISSUE TITLE
getGeoPos errors with GPT

### ISSUE THREAD

**Issue by eric542** [senbox-org/s1tbx#58]
Hi,

I have installed SNAP 6.0 and recently (couple of weeks ago) updated it as per [these instructions](https://senbox.atlassian.net/wiki/spaces/SNAP/pages/30539785/Update+SNAP+from+the+command+line).

I now get a whole lot of “errors” when processing S1 backscatter data with GPT:

[…]
getGeoPos: Maximum number of iterations reached for pixel (26684.0, 0.0)
getGeoPos: Maximum number of iterations reached for pixel (26704.0, 0.0)
getGeoPos: Maximum number of iterations reached for pixel (26724.0, 0.0)
x = 26144.0, y = 20.0, lat = -33.56962942107605, lon = 146.9941624206096, iter = 1, x’ = 26144.656455993652, y’ = 19.995193234967033
x = 26164.0, y = 20.0, lat = -33.56909570334282, lon = 146.99204892309245, iter = 1, x’ = 26164.626922607422, y’ = 19.994609368615418
x = 26184.0, y = 20.0, lat = -33.56857201643739, lon = 146.9899748135287, iter = 1, x’ = 26184.444358825684, y’ = 19.99455628985618
[…]

GPT generates literally millions of such lines (all starting with either "getGeoPos" or "x = " as above), which is a problem as I am processing the SAR scenes on high-performance computing facilities. This means that the processing outputs from GPT get logged to a file for inspection after the job execution, and therefore generates gigabytes of log data to file for each processed scene.

There does not appear to be anything wrong with the processing otherwise, and the SAR data seems to be processed and written to disk correctly. The above messages are not giving me any hint either as to where the problem might be.

Can anyone comment on where this issue might come from? And how to fix it?

Thanks in advance for your help!

**Comment by eric542** [comment]
@marpet Thanks very much for the response.

And yes, sorry, I wasn't very clear regarding the 'GPT version'... This is the version nr that's provided when executing a GPT processing command, e.g. 

`gpt backsc_proc_graph.xml [...]`

This generates the following output on the command line:

```
Executing processing graph
version = 2.84
....10%....20%....30%....40%....50%....60%....70%....80%....90%done.
```

I thought it might be useful to report that version of the SW here...

**Comment by anthony-scarth** [comment]
Hi. I think this relates to a change in S1 Toolbox v6.0.5 with the Terrain Flattening operator, and not GPT at all. Specifically, it looks like [this commit](https://github.com/senbox-org/s1tbx/commit/af4827a44db40ba3b5688ebd3bcc94fe5cdd80e7) is responsible for adding the new print statements that you are seeing. I don't think these are 'errors' as the result seems to be correct.

However, I have been experiencing issues with this commit as it seems to have introduced a significant slowdown in processing times, which I have brought up on [the forums](https://forum.step.esa.int/t/performance-regression-with-terrain-flattening-re-grid/13306?u=anthony.scarth). Should I create a new issue for this, or can we continue in this thread?

**Comment by grousel** [comment]
We are consolidating issue tracking in JIRA.  This item is tracked as https://senbox.atlassian.net/browse/SITBX-595 going forward
