### ISSUE TITLE
Bug in Radar > Interferometric > Unwrapping > Snaphu Export pane, SanphuExport tab

### ISSUE THREAD

**Issue by funkenbeachin** [senbox-org/s1tbx#59]
Bug in Radar > Interferometric > Unwrapping > Snaphu Export pane, SanphuExport tab. Cannot select Target folder with the navigation button. When the tab is opened, 'Error … Please add a target folder' appears. When a folder is selected, the button says “Open”. In that folder, the Select button does nothing.

Work-around is to type a folder address or copy the folder path into the copy buffer, use Ctrl-V to paste in the into the Target folder box.

**Comment by grousel** [comment]
We are consolidating reports into JIRA.  Going forward this item is tracked as https://senbox.atlassian.net/browse/SITBX-594
