### ISSUE TITLE
gpt.bat does not work on 32 bit Windows installations

### ISSUE THREAD

**Issue by radosuav** [senbox-org/s1tbx#6]
Hi

gpt.bat does not work on 32 bit Windows installations. This was tested on multiple Windows versions and with S1TBX 1.1.0 and 1.1.1. When calling gpt.bat from command line the following error appears:

Unrecognised VM option 'UseLoopPredicate'
Error: Could not create the Java Virtual Machine
Error: A fatal exception has occurred. Program will exit.

Of course it can be fixed by removing 'UseLoopPredicate' option from gpt.bat but it would be better if it worked straight out of the box.

Thanks

PS
I wanted to report this issue using the link at the bottom of https://sentinel.esa.int/web/sentinel/toolboxes/sentinel-1 but got an error message about the value of pid field. So I hope that reporting it here is fine as well.

**Comment by lveci** [comment]
Thanks, I've updated the 32-bit options
