### ISSUE TITLE
Performance Regression with Terrain Flattening Regrid in S1TBX v6.0.5

### ISSUE THREAD

**Issue by anthony-scarth** [senbox-org/s1tbx#60]
I have been experiencing issues with the performance of terrain flattening in the latest version of S1TBX (6.0.5), which is probably related to [this commit](https://github.com/senbox-org/s1tbx/commit/af4827a44db40ba3b5688ebd3bcc94fe5cdd80e7). I have detailed the slowdown that I have experienced on [the forums](https://forum.step.esa.int/t/performance-regression-with-terrain-flattening-re-grid/13306?u=anthony.scarth). 

Output seems to be relatively consistent with previous versions so I don't think there are any technical issues. However, can the additional code please be reverted or optimised as the processing is taking about four times as long as it did previously?

**Comment by grousel** [comment]
We are consolidating our issue tracking in JIRA.  Currently we are improving Terrain Flattening and so I've added this report to the item for the improvement.  https://senbox.atlassian.net/browse/SITBX-561
