### ISSUE TITLE
ALOS-2 calibration is wrong

### ISSUE THREAD

**Issue by yuvalutilis** [senbox-org/s1tbx#61]
the calibrator for ALOS-2 is not properly right.

https://github.com/senbox-org/s1tbx/blob/master/s1tbx-op-calibration/src/main/java/org/esa/s1tbx/calibration/gpf/calibrators/ALOSCalibrator.java

Complex data calibration for ALOS-2 has two calibration factor -83 & -32. Hence calibration factor for complex data should be -115.
https://www.eorc.jaxa.jp/ALOS-2/en/calval/calval_index.htm

This should only be applied as a subtraction on the converted data to dB (log to linear).

The use in line 233
 sigma = dn * calibrationFactor;

is completely wrong and diverts the data.

For your attention and fix

Thanks,

Yuval

**Comment by lveci** [comment]
The calibration factor for complex product is -115 dB, but we've used it in linear scale. The dB to linear conversion is in line 116.

**Comment by yuvalutilis** [comment]
Many thanks @lveci , apologies i realized what is my mistake.

**Comment by lveci** [comment]
Thanks @yuvalutilis I'm glad you're checking the code
