### ISSUE TITLE
Expose onlyTopoRefPhase variable in the GUI of SNAP

### ISSUE THREAD

**Issue by davosnitti** [senbox-org/s1tbx#62]
Dear s1tbx developers,
in the source file TopoPhase.java (repo: s1tbx/jlinda) I see that value 1 is statically assigned to the boolean variable “onlyTopoRefPhase”.
Is it possible to expose the variable in the SNAP GUI (e.g., in the SubtRefDemOpUI.java), in order to allow the user to select 0 or 1 for it?
Actually, I prefer to set this variable to 0, instead of 1, thus including the flat-earth phase contribution in the topographic phase contribution.
Waiting for your feedback or suggestions, I thank you in advance
Best regards
Davide

**Comment by grousel** [comment]
Hello, thank you for the report.  We are moving our issue tracking into JIRA so please reference https://senbox.atlassian.net/browse/SITBX-593 for further updates.
